import { pageUrlForFile } from './pageUrlForFile.ts'
import { parseRouteSegments } from './parseRouteSegments.ts'

/*
Walks a `[name]` / `[...rest]` route URL and returns the param shape it
declares. Catch-all segments map to `string` under their declared name —
the server's toBunRoutePattern renames Bun's `*` key back to that name
when dispatching, so the page component sees `params.rest`, not
`params['*']`.
*/
function paramsForRoute(routeUrl: string): Record<string, 'string'> {
    return Object.fromEntries(
        parseRouteSegments(routeUrl)
            .filter((segment) => segment.kind === 'param')
            .map((segment) => [segment.name, 'string'] as const),
    )
}

function renderParamsShape(shape: Record<string, 'string'>): string {
    const keys = Object.keys(shape)
    if (keys.length === 0) {
        return 'Record<string, never>'
    }
    return `{ ${keys.map((key) => `${JSON.stringify(key)}: string`).join('; ')} }`
}

/*
Emits a `.d.ts` that augments belte's `Routes` interface with one entry per
page file in the project. Page picks this up as a discriminated union keyed
on `route`, so `if (page.route === '/media/[id]') page.params.id` is typed
automatically without consumers writing route types by hand.
The file is written to `src/.belte/routes.d.ts` so the consumer's existing
src tsconfig include picks it up with no extra configuration. The augmented
module is keyed on the name the project imports belte under (`importName`),
so the augmentation matches the consumer's `page` import whether belte is
installed directly (`@belte/belte`) or behind an alias.
*/
export async function writeRoutesDts({
    cwd,
    pageFiles,
    importName,
}: {
    cwd: string
    pageFiles: string[]
    importName: string
}): Promise<void> {
    const entries = pageFiles
        .map((file) => ({
            route: pageUrlForFile(file),
            params: paramsForRoute(pageUrlForFile(file)),
        }))
        .toSorted((a, b) => a.route.localeCompare(b.route))
        .map(
            ({ route, params }) => `        ${JSON.stringify(route)}: ${renderParamsShape(params)}`,
        )
        .join('\n')
    const contents = `// Generated by belte. Do not edit by hand.
declare module '${importName}/browser/page' {
    interface Routes {
${entries}
    }
}

export {}
`
    await Bun.write(`${cwd}/src/.belte/routes.d.ts`, contents)
}
